---
title: "git_00"
author: "Gema Garcia"
date: "Year 2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with a sequence of commits to the master branch.
Our project will be done using several commits to the master branch.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->
He took his vorpal sword in hand:  
Long time the manxome foe he sought  
So rested he by the Tumtum tree,  
And stood awhile in thought.  
And, as in uffish thought he stood,  

## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->
A trees leaves may be ever so good  
So may it's bar, so may it's wood;  
but unless you put thr right thing to it's root  
It never will show much flower or fruit.  
But I may be one who does not care  

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->
The sun was shining on the sea,  
Shining with all his might:  
He did his very best to make  
The billows smooth and bright —  
And this was odd, because it was  
The middle of the night.  
The moon was shining sulkily,  
Because she thought the sun  
Had got no business to be there  
After the day was done —  
"It's very rude of him," she said,  
"To come and spoil the fun."  

## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->
did you think I was a city
big enough for a weekend get away 
I am the town surrounding it
the one you've never heard of 
but always pass through 
there are no neon lights here 
no skyscrapers or statues
but there is thunder
for I make bridges tr
